[ids]

*

[main]
f = overloadt(control, f, 200)
j = overloadt(control, j, 200)
k = overloadt(alt, k, 200)
d = overloadt(alt, d, 200)
s = overloadt(meta, s, 200)
l = overloadt(meta, l, 200)


leftalt = overload(shift, backspace) 
rightalt = overload(altgr, delete)

space = overloadt(nav, space, 200)

[nav]
h = left
j = down
s = up
l = right

y = home
o = end
u = pagedown
i = pageup

q = tab
b = S-tab

u = 1
i = 2
e = 3
m = 4
p = 5
o = 6
y = 7
x = 8
. = 9
, = 0
b = ,
a = .

rightalt = enter
leftalt = esc

[dk]
e = è
i = é
u = ù
  = ’
  ai_…ŷiiuu
  
